package:
  name: appuqa
  version: "0.0.2"

source:
  git_rev: v0.0.2
  git_url: https://github.com/DeanLym/UnifiedUQFramework.git

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - numpy
    
