package:
  name: appuqa
  version: "0.1.0"

source:
  git_rev: v0.1.0
  git_url: https://github.com/DeanLym/UnifiedUQFramework.git

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - numpy
    
